
[build]
  publish = "build"
  functions = "netlify/functions"

[functions]
  included_files = [
    "/home/fabs/fabulous-apps/cbg/la-historia/netlify/functions/stats/1979-80_stats.ods",
    "/home/fabs/fabulous-apps/cbg/la-historia/netlify/functions/stats/1980-81_stats.ods"
  ]
